

CREATE TABLE DEPARTAMENTOS(
    ID_DEPARTAMENTO INTEGER PRIMARY KEY,
    NOME_DEPAR VARCHAR(100),
    HORA_FUNCIO VARCHAR(50),
    SALARIO VARCHAR(50)
);
    
CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARTIO INTEGER PRIMARY KEY,
    NOME VARCHAR(100),
    RG VARCHAR(14),
    DATA_NAS DATETIME,
    DATA_CON DATETIME,
    ID_DEPARTAMENTO INTEGER,
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO)
);

CREATE TABLE GERENTE(
    ID_GERENTE INTEGER PRIMARY KEY,
    HORA_TRABALHO VARCHAR(50),
    SALARIO VARCHAR(50),
    FUNCIONARIO INTEGER,
    FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARTIO)
);

CREATE TABLE PRODUTO(
    CB INTEGER PRIMARY KEY,
    PREÇO INTEGER,
    STOCK INTEGER,
    DATA_VALIDADE DATETIME
);

CREATE TABLE FORNEÇEDOR(
    CNPJ VARCHAR(50) PRIMARY KEY,
    NOME VARCHAR(50),
    TELEFONE VARCHAR(50)
);

CREATE TABLE COMPRA(
    DATA_COMPRA DATETIME,
    QTDE INTEGER,
    VALOR_TOTAL INTEGER,
    CNPJ_FORNEÇEDOR VARCHAR(50),
    CB_PRODUTO INTEGER,
    FOREIGN KEY (CNPJ_FORNEÇEDOR) REFERENCES FORNEÇEDOR (CNPJ),
    FOREIGN KEY (CB_PRODUTO) REFERENCES PRODUTO (CB),
    PRIMARY KEY (CNPJ_FORNEÇEDOR, CB_PRODUTO)
);

CREATE TABLE PET(
    NOME VARCHAR(50) PRIMARY KEY,
    ESPECIE VARCHAR(50),
    RAÇA VARCHAR(50)
);

CREATE TABLE CLIENTES(
    RG VARCHAR(50) PRIMARY KEY,
    NOME VARCHAR(100),
    DATA_NAS DATETIME,
    NOME_PET VARCHAR(50) NOT NULL,
    FOREIGN KEY (NOME_PET) REFERENCES PET(NOME)   
);

CREATE TABLE VENDAS(
    QTDE INTEGER,
    VALOR_TOTAL INTEGER,
    DATA_VENDA DATETIME,
    DEPARTAMENTO INTEGER,
    PRODUTO INTEGER,
    CLIENTE VARCHAR(50),
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),  
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(CB), 
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(RG),  
    PRIMARY KEY (DEPARTAMENTO,PRODUTO,CLIENTE)
);


